# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'app/ui/loginWindow/Ui_loginWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_loginWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(750, 500)

        # Set background color to blue
        MainWindow.setStyleSheet("background-color: #1E90FF;")

        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        # Email input
        self.email_input = QtWidgets.QLineEdit(self.centralwidget)
        self.email_input.setGeometry(QtCore.QRect(240, 200, 271, 30))  # Aumentata altezza
        self.email_input.setObjectName("email_input")
        self.email_input.setStyleSheet("""
            background-color: white; 
            color: #1E90FF;
            padding: 5px;
            border-radius: 3px;
        """)

        # Password input
        self.password_input = QtWidgets.QLineEdit(self.centralwidget)
        self.password_input.setGeometry(QtCore.QRect(240, 240, 271, 30))  # Aumentata altezza
        self.password_input.setObjectName("password_input")
        self.password_input.setStyleSheet("""
            background-color: white; 
            color: #1E90FF;
            padding: 5px;
            border-radius: 3px;
        """)
        self.password_input.setEchoMode(QtWidgets.QLineEdit.Password)

        # Login button (ingrandito)
        self.login_button = QtWidgets.QPushButton(self.centralwidget)
        self.login_button.setGeometry(QtCore.QRect(240, 290, 271, 40))  # Aumentata altezza
        self.login_button.setObjectName("login_button")
        self.login_button.setStyleSheet(
            "QPushButton {"
            "   background-color: white;"
            "   color: #1E90FF;"
            "   font-weight: bold;"
            "   border-radius: 5px;"
            "   padding: 8px;"
            "}"
            "QPushButton:hover {"
            "   background-color: #F0F0F0;"
            "}"
        )

        # Error message label (tra login e reset password)
        self.error_label = QtWidgets.QLabel(self.centralwidget)
        self.error_label.setGeometry(QtCore.QRect(240, 340, 271, 30))
        self.error_label.setObjectName("error_label")
        self.error_label.setStyleSheet("""
            color: white; 
            font-weight: bold;
            qproperty-alignment: AlignCenter;
        """)
        self.error_label.setText("")

        # Reset password button (ingrandito e riposizionato)
        self.reset_password_button = QtWidgets.QPushButton(self.centralwidget)
        self.reset_password_button.setGeometry(QtCore.QRect(240, 380, 271, 40))  # Aumentata altezza
        self.reset_password_button.setObjectName("reset_password_button")
        self.reset_password_button.setStyleSheet(
            "QPushButton {"
            "   background-color: white;"
            "   color: #1E90FF;"
            "   font-weight: bold;"
            "   border-radius: 5px;"
            "   padding: 8px;"
            "}"
            "QPushButton:hover {"
            "   background-color: #F0F0F0;"
            "}"
        )

        # Main title label (centrato)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 70, 750, 81))  # Larghezza a tutta la finestra
        self.label.setObjectName("label")
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(30)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setStyleSheet("""
            color: white; 
            qproperty-alignment: AlignCenter;
        """)

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 42))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Login - EVENTICA"))
        self.email_input.setPlaceholderText(_translate("MainWindow", "Email"))
        self.password_input.setPlaceholderText(_translate("MainWindow", "Password"))
        self.login_button.setText(_translate("MainWindow", "Login"))
        self.label.setText(_translate("MainWindow", "EVENTICA"))
        self.reset_password_button.setText(_translate("MainWindow", "Password dimenticata?"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)

    # Load Montserrat font if available
    font_db = QtGui.QFontDatabase()
    if "Montserrat" not in font_db.families():
        # If Montserrat is not available, fall back to Arial
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        app.setFont(font)

    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_loginWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())